//
// CategoriesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CategoriesAPI {

    /**
     Create category
     
     - parameter categoryWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Category
     */
    open class func createCategory(categoryWrite: CategoryWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> Category {
        return try await createCategoryWithRequestBuilder(categoryWrite: categoryWrite, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create category
     - POST /v1/categories
     - Creates a new category and returns the created resource with its assigned ID.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [Location(String)]
     - parameter categoryWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Category> 
     */
    open class func createCategoryWithRequestBuilder(categoryWrite: CategoryWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Category> {
        let localVariablePath = "/v1/categories"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: categoryWrite, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Category>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete category
     
     - parameter categoryId: (path) Category UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteCategory(categoryId: UUID, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteCategoryWithRequestBuilder(categoryId: categoryId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete category
     - DELETE /v1/categories/{categoryId}
     - Permanently deletes a category by its UUID.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter categoryId: (path) Category UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCategoryWithRequestBuilder(categoryId: UUID, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/categories/{categoryId}"
        let categoryIdPreEscape = "\(APIHelper.mapValueToPathItem(categoryId))"
        let categoryIdPostEscape = categoryIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{categoryId}", with: categoryIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get category
     
     - parameter categoryId: (path) Category UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Category
     */
    open class func getCategory(categoryId: UUID, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> Category {
        return try await getCategoryWithRequestBuilder(categoryId: categoryId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get category
     - GET /v1/categories/{categoryId}
     - Returns a single category by its UUID.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter categoryId: (path) Category UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Category> 
     */
    open class func getCategoryWithRequestBuilder(categoryId: UUID, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Category> {
        var localVariablePath = "/v1/categories/{categoryId}"
        let categoryIdPreEscape = "\(APIHelper.mapValueToPathItem(categoryId))"
        let categoryIdPostEscape = categoryIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{categoryId}", with: categoryIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Category>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List categories
     
     - parameter page: (query) Zero-based page number. (optional, default to 0)
     - parameter size: (query) Maximum number of items to return. (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PaginatedCategories
     */
    open class func listCategories(page: Int? = nil, size: Int? = nil, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> PaginatedCategories {
        return try await listCategoriesWithRequestBuilder(page: page, size: size, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List categories
     - GET /v1/categories
     - Returns a paginated list of categories for the authenticated user.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter page: (query) Zero-based page number. (optional, default to 0)
     - parameter size: (query) Maximum number of items to return. (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PaginatedCategories> 
     */
    open class func listCategoriesWithRequestBuilder(page: Int? = nil, size: Int? = nil, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<PaginatedCategories> {
        let localVariablePath = "/v1/categories"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "size": (wrappedValue: size?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedCategories>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Replace category
     
     - parameter categoryId: (path) Category UUID 
     - parameter categoryWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Category
     */
    open class func replaceCategory(categoryId: UUID, categoryWrite: CategoryWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> Category {
        return try await replaceCategoryWithRequestBuilder(categoryId: categoryId, categoryWrite: categoryWrite, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Replace category
     - PUT /v1/categories/{categoryId}
     - Fully replaces a category's data (PUT semantics).
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter categoryId: (path) Category UUID 
     - parameter categoryWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Category> 
     */
    open class func replaceCategoryWithRequestBuilder(categoryId: UUID, categoryWrite: CategoryWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Category> {
        var localVariablePath = "/v1/categories/{categoryId}"
        let categoryIdPreEscape = "\(APIHelper.mapValueToPathItem(categoryId))"
        let categoryIdPostEscape = categoryIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{categoryId}", with: categoryIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: categoryWrite, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Category>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Partially update category
     
     - parameter categoryId: (path) Category UUID 
     - parameter categoryUpdate: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Category
     */
    open class func updateCategory(categoryId: UUID, categoryUpdate: CategoryUpdate, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> Category {
        return try await updateCategoryWithRequestBuilder(categoryId: categoryId, categoryUpdate: categoryUpdate, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Partially update category
     - PATCH /v1/categories/{categoryId}
     - Partially updates a category; only provided fields are modified. Empty patch objects are invalid and return 400.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter categoryId: (path) Category UUID 
     - parameter categoryUpdate: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Category> 
     */
    open class func updateCategoryWithRequestBuilder(categoryId: UUID, categoryUpdate: CategoryUpdate, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Category> {
        var localVariablePath = "/v1/categories/{categoryId}"
        let categoryIdPreEscape = "\(APIHelper.mapValueToPathItem(categoryId))"
        let categoryIdPostEscape = categoryIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{categoryId}", with: categoryIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: categoryUpdate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Category>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
