//
// TransactionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class TransactionsAPI {

    /**
     Create transaction
     
     - parameter transactionWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Transaction
     */
    open class func createTransaction(transactionWrite: TransactionWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> Transaction {
        return try await createTransactionWithRequestBuilder(transactionWrite: transactionWrite, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create transaction
     - POST /v1/transactions
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [Location(String)]
     - parameter transactionWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Transaction> 
     */
    open class func createTransactionWithRequestBuilder(transactionWrite: TransactionWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Transaction> {
        let localVariablePath = "/v1/transactions"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: transactionWrite, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Transaction>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete transaction
     
     - parameter transactionId: (path) Transaction UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteTransaction(transactionId: UUID, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteTransactionWithRequestBuilder(transactionId: transactionId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete transaction
     - DELETE /v1/transactions/{transactionId}
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter transactionId: (path) Transaction UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteTransactionWithRequestBuilder(transactionId: UUID, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/transactions/{transactionId}"
        let transactionIdPreEscape = "\(APIHelper.mapValueToPathItem(transactionId))"
        let transactionIdPostEscape = transactionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{transactionId}", with: transactionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get transaction
     
     - parameter transactionId: (path) Transaction UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Transaction
     */
    open class func getTransaction(transactionId: UUID, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> Transaction {
        return try await getTransactionWithRequestBuilder(transactionId: transactionId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get transaction
     - GET /v1/transactions/{transactionId}
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter transactionId: (path) Transaction UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Transaction> 
     */
    open class func getTransactionWithRequestBuilder(transactionId: UUID, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Transaction> {
        var localVariablePath = "/v1/transactions/{transactionId}"
        let transactionIdPreEscape = "\(APIHelper.mapValueToPathItem(transactionId))"
        let transactionIdPostEscape = transactionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{transactionId}", with: transactionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Transaction>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_listTransactions: String, Sendable, CaseIterable {
        case asc = "asc"
        case desc = "desc"
    }

    /**
     List transactions
     
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - parameter categoryId: (query) Filter by category (optional)
     - parameter start: (query) Inclusive start date (optional)
     - parameter end: (query) Inclusive end date (optional)
     - parameter sort: (query) Sort order (by date) (optional, default to .desc)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PaginatedTransactions
     */
    open class func listTransactions(limit: Int? = nil, offset: Int? = nil, categoryId: UUID? = nil, start: Date? = nil, end: Date? = nil, sort: Sort_listTransactions? = nil, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> PaginatedTransactions {
        return try await listTransactionsWithRequestBuilder(limit: limit, offset: offset, categoryId: categoryId, start: start, end: end, sort: sort, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List transactions
     - GET /v1/transactions
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - parameter categoryId: (query) Filter by category (optional)
     - parameter start: (query) Inclusive start date (optional)
     - parameter end: (query) Inclusive end date (optional)
     - parameter sort: (query) Sort order (by date) (optional, default to .desc)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PaginatedTransactions> 
     */
    open class func listTransactionsWithRequestBuilder(limit: Int? = nil, offset: Int? = nil, categoryId: UUID? = nil, start: Date? = nil, end: Date? = nil, sort: Sort_listTransactions? = nil, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<PaginatedTransactions> {
        let localVariablePath = "/v1/transactions"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "categoryId": (wrappedValue: categoryId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "start": (wrappedValue: start?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "end": (wrappedValue: end?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedTransactions>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Replace transaction
     
     - parameter transactionId: (path) Transaction UUID 
     - parameter transactionWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Transaction
     */
    open class func replaceTransaction(transactionId: UUID, transactionWrite: TransactionWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> Transaction {
        return try await replaceTransactionWithRequestBuilder(transactionId: transactionId, transactionWrite: transactionWrite, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Replace transaction
     - PUT /v1/transactions/{transactionId}
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter transactionId: (path) Transaction UUID 
     - parameter transactionWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Transaction> 
     */
    open class func replaceTransactionWithRequestBuilder(transactionId: UUID, transactionWrite: TransactionWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Transaction> {
        var localVariablePath = "/v1/transactions/{transactionId}"
        let transactionIdPreEscape = "\(APIHelper.mapValueToPathItem(transactionId))"
        let transactionIdPostEscape = transactionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{transactionId}", with: transactionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: transactionWrite, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Transaction>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Partially update transaction
     
     - parameter transactionId: (path) Transaction UUID 
     - parameter transactionUpdate: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Transaction
     */
    open class func updateTransaction(transactionId: UUID, transactionUpdate: TransactionUpdate, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> Transaction {
        return try await updateTransactionWithRequestBuilder(transactionId: transactionId, transactionUpdate: transactionUpdate, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Partially update transaction
     - PATCH /v1/transactions/{transactionId}
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter transactionId: (path) Transaction UUID 
     - parameter transactionUpdate: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Transaction> 
     */
    open class func updateTransactionWithRequestBuilder(transactionId: UUID, transactionUpdate: TransactionUpdate, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Transaction> {
        var localVariablePath = "/v1/transactions/{transactionId}"
        let transactionIdPreEscape = "\(APIHelper.mapValueToPathItem(transactionId))"
        let transactionIdPostEscape = transactionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{transactionId}", with: transactionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: transactionUpdate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Transaction>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
