//
// AuthToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuthToken: Sendable, Codable, Hashable {

    /** JWT access token used in the Authorization header for subsequent requests. */
    public var accessToken: String
    /** Token type, always \"Bearer\". */
    public var tokenType: String
    /** Lifetime of the access token in seconds. */
    public var expiresIn: Int
    /** Opaque refresh token */
    public var refreshToken: String
    /** Space-separated list of granted scopes, if applicable */
    public var scope: String?

    public init(accessToken: String, tokenType: String, expiresIn: Int, refreshToken: String, scope: String? = nil) {
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresIn = expiresIn
        self.refreshToken = refreshToken
        self.scope = scope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case refreshToken = "refresh_token"
        case scope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(tokenType, forKey: .tokenType)
        try container.encode(expiresIn, forKey: .expiresIn)
        try container.encode(refreshToken, forKey: .refreshToken)
        try container.encodeIfPresent(scope, forKey: .scope)
    }
}

