//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Category: Sendable, Codable, Hashable {

    /** Unique identifier for the category. */
    public var id: UUID
    /** Human-readable name of the category. */
    public var name: String
    /** ISO 8601 timestamp when the category was created. */
    public var createdAt: Date?
    /** ISO 8601 timestamp when the category was last updated. */
    public var updatedAt: Date?

    public init(id: UUID, name: String, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


extension Category: Identifiable {}
