//
// CategorySpendingSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CategorySpendingSummary: Sendable, Codable, Hashable {

    public static let monthRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^\\d{4}-(0[1-9]|1[0-2])$/")
    public static let currencyRule = StringRule(minLength: 3, maxLength: 3, pattern: "/^[A-Z]{3}$/")
    /** Calendar month echoed back from the request, formatted YYYY-MM. */
    public var month: String
    /** ISO 4217 currency code echoed back from the request. */
    public var currency: String
    /** One row per category owned by the authenticated user, including categories with zero spending. */
    public var items: [CategorySpendingRow]

    public init(month: String, currency: String, items: [CategorySpendingRow]) {
        self.month = month
        self.currency = currency
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case month
        case currency
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(month, forKey: .month)
        try container.encode(currency, forKey: .currency)
        try container.encode(items, forKey: .items)
    }
}

