//
// CategoryUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Patch request — only provided fields are updated. At least one field must be provided. */
public struct CategoryUpdate: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    /** New human-readable name for the category (1–255 characters). */
    public var name: String?

    public init(name: String? = nil) {
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

