//
// FieldError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FieldError: Sendable, Codable, Hashable {

    /** Name of the field that caused the error. */
    public var field: String
    /** Human-readable error message for the field. */
    public var message: String

    public init(field: String, message: String) {
        self.field = field
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(field, forKey: .field)
        try container.encode(message, forKey: .message)
    }
}

