//
// MonthlySummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MonthlySummary: Sendable, Codable, Hashable {

    public static let monthRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^\\d{4}-(0[1-9]|1[0-2])$/")
    public static let currencyRule = StringRule(minLength: 3, maxLength: 3, pattern: "/^[A-Z]{3}$/")
    public static let incomeRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let expenseRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let incomeCountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let expenseCountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let excludedTransactionCountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Calendar month echoed back from the request, formatted YYYY-MM. */
    public var month: String
    /** ISO 4217 currency code echoed back from the request. */
    public var currency: String
    /** Sum of INCOME transactions in the requested currency for this month, in minor units. */
    public var income: Int64
    /** Sum of EXPENSE transactions in the requested currency for this month, in minor units. */
    public var expense: Int64
    /** income minus expense, in minor units. May be negative. */
    public var balance: Int64
    /** Number of INCOME transactions contributing to `income`. */
    public var incomeCount: Int
    /** Number of EXPENSE transactions contributing to `expense`. */
    public var expenseCount: Int
    /** Number of transactions (INCOME or EXPENSE) in this month whose currency did not match the requested currency and were therefore not summed. */
    public var excludedTransactionCount: Int

    public init(month: String, currency: String, income: Int64, expense: Int64, balance: Int64, incomeCount: Int, expenseCount: Int, excludedTransactionCount: Int) {
        self.month = month
        self.currency = currency
        self.income = income
        self.expense = expense
        self.balance = balance
        self.incomeCount = incomeCount
        self.expenseCount = expenseCount
        self.excludedTransactionCount = excludedTransactionCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case month
        case currency
        case income
        case expense
        case balance
        case incomeCount
        case expenseCount
        case excludedTransactionCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(month, forKey: .month)
        try container.encode(currency, forKey: .currency)
        try container.encode(income, forKey: .income)
        try container.encode(expense, forKey: .expense)
        try container.encode(balance, forKey: .balance)
        try container.encode(incomeCount, forKey: .incomeCount)
        try container.encode(expenseCount, forKey: .expenseCount)
        try container.encode(excludedTransactionCount, forKey: .excludedTransactionCount)
    }
}

