//
// PaginatedCategories.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedCategories: Sendable, Codable, Hashable {

    /** The categories on the current page. */
    public var items: [Category]
    /** Pagination metadata for the current response. */
    public var meta: PaginationMeta

    public init(items: [Category], meta: PaginationMeta) {
        self.items = items
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(meta, forKey: .meta)
    }
}

