//
// PaginationMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginationMeta: Sendable, Codable, Hashable {

    /** Zero-based page number returned in this response. */
    public var page: Int
    /** The page size used for this response. */
    public var size: Int
    /** Total number of items matching the request across all pages. */
    public var total: Int64

    public init(page: Int, size: Int, total: Int64) {
        self.page = page
        self.size = size
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case size
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encode(size, forKey: .size)
        try container.encode(total, forKey: .total)
    }
}

