//
// PaginationMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginationMeta: Sendable, Codable, Hashable {

    public var limit: Int
    public var offset: Int
    public var total: Int64

    public init(limit: Int, offset: Int, total: Int64) {
        self.limit = limit
        self.offset = offset
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limit
        case offset
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(limit, forKey: .limit)
        try container.encode(offset, forKey: .offset)
        try container.encode(total, forKey: .total)
    }
}

