//
// Problem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** RFC 7807 Problem+JSON */
public struct Problem: Sendable, Codable, Hashable {

    public var type: String? = "about:blank"
    public var title: String
    public var status: Int
    public var detail: String?
    public var instance: String?

    public init(type: String? = "about:blank", title: String, status: Int, detail: String? = nil, instance: String? = nil) {
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.instance = instance
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case title
        case status
        case detail
        case instance
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(title, forKey: .title)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(instance, forKey: .instance)
    }
}

