//
// Problem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** RFC 9457 Problem Details */
public struct Problem: Sendable, Codable, Hashable {

    /** URI that identifies the problem type. Defaults to \"about:blank\" when not set. */
    public var type: String? = "about:blank"
    /** Short, human-readable summary of the problem type. */
    public var title: String
    /** HTTP status code for this occurrence of the problem. */
    public var status: Int
    /** Human-readable explanation specific to this occurrence of the problem. */
    public var detail: String?
    /** URI reference identifying the specific occurrence of the problem. */
    public var instance: String?
    /** Optional list of specific errors (e.g., field-level validation errors). */
    public var errors: [FieldError]?

    public init(type: String? = "about:blank", title: String, status: Int, detail: String? = nil, instance: String? = nil, errors: [FieldError]? = nil) {
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.instance = instance
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case title
        case status
        case detail
        case instance
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(title, forKey: .title)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(instance, forKey: .instance)
        try container.encodeIfPresent(errors, forKey: .errors)
    }
}

