//
// RegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterRequest: Sendable, Codable, Hashable {

    public static let usernameRule = StringRule(minLength: 3, maxLength: 50, pattern: nil)
    public static let passwordRule = StringRule(minLength: 8, maxLength: nil, pattern: nil)
    /** Unique username chosen by the user (3–50 characters). */
    public var username: String
    /** Account password (minimum 8 characters). */
    public var password: String

    public init(username: String, password: String) {
        self.username = username
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(password, forKey: .password)
    }
}

