//
// TransactionWrite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TransactionWrite: Sendable, Codable, Hashable {

    public static let amountRule = NumericRule<Int64>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let currencyRule = StringRule(minLength: 3, maxLength: 3, pattern: "/^[A-Z]{3}$/")
    public static let descriptionRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    /** UUID of the category this transaction belongs to. */
    public var categoryId: UUID
    /** Amount in minor units (e.g. 1299 = €12.99). Must be at least 1. */
    public var amount: Int64
    /** Whether this transaction is an outgoing expense or incoming income. */
    public var type: TransactionType
    /** ISO 4217 three-letter currency code. */
    public var currency: String
    /** Date on which the transaction occurred (YYYY-MM-DD). */
    public var date: Date
    /** Optional free-text note for the transaction (up to 255 characters). */
    public var description: String?

    public init(categoryId: UUID, amount: Int64, type: TransactionType, currency: String, date: Date, description: String? = nil) {
        self.categoryId = categoryId
        self.amount = amount
        self.type = type
        self.currency = currency
        self.date = date
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryId
        case amount
        case type
        case currency
        case date
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(amount, forKey: .amount)
        try container.encode(type, forKey: .type)
        try container.encode(currency, forKey: .currency)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

