//
// TransactionUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Patch request — only provided fields will be updated */
public struct TransactionUpdate: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case expense = "EXPENSE"
        case income = "INCOME"
    }
    public static let amountRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let currencyRule = StringRule(minLength: 3, maxLength: 3, pattern: nil)
    public var categoryId: UUID?
    public var amount: Int?
    public var type: ModelType?
    public var currency: String?
    public var date: Date?
    public var description: String?

    public init(categoryId: UUID? = nil, amount: Int? = nil, type: ModelType? = nil, currency: String? = nil, date: Date? = nil, description: String? = nil) {
        self.categoryId = categoryId
        self.amount = amount
        self.type = type
        self.currency = currency
        self.date = date
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryId
        case amount
        case type
        case currency
        case date
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

