//
// Transaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Transaction: Sendable, Codable, Hashable {

    public static let currencyRule = StringRule(minLength: 3, maxLength: 3, pattern: "/^[A-Z]{3}$/")
    public static let descriptionRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    /** Unique identifier for the transaction. */
    public var id: UUID
    /** UUID of the category this transaction belongs to. */
    public var categoryId: UUID
    /** Amount in minor units (e.g. 1299 = €12.99). */
    public var amount: Int64
    /** Whether this transaction is an outgoing expense or incoming income. */
    public var type: TransactionType
    /** ISO 4217 three-letter currency code. */
    public var currency: String
    /** Date on which the transaction occurred (YYYY-MM-DD). */
    public var date: Date
    /** Optional free-text note for the transaction (up to 255 characters). */
    public var description: String?
    /** ISO 8601 timestamp when the transaction record was created. */
    public var createdAt: Date?
    /** ISO 8601 timestamp when the transaction record was last updated. */
    public var updatedAt: Date?

    public init(id: UUID, categoryId: UUID, amount: Int64, type: TransactionType, currency: String, date: Date, description: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.categoryId = categoryId
        self.amount = amount
        self.type = type
        self.currency = currency
        self.date = date
        self.description = description
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case categoryId
        case amount
        case type
        case currency
        case date
        case description
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(amount, forKey: .amount)
        try container.encode(type, forKey: .type)
        try container.encode(currency, forKey: .currency)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


extension Transaction: Identifiable {}
