//
// Transaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Transaction: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case expense = "EXPENSE"
        case income = "INCOME"
    }
    public static let currencyRule = StringRule(minLength: 3, maxLength: 3, pattern: nil)
    public var id: UUID
    public var categoryId: UUID
    /** Amount in minor units */
    public var amount: Int64
    public var type: ModelType
    public var currency: String
    public var date: Date
    public var description: String?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: UUID, categoryId: UUID, amount: Int64, type: ModelType, currency: String, date: Date, description: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.categoryId = categoryId
        self.amount = amount
        self.type = type
        self.currency = currency
        self.date = date
        self.description = description
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case categoryId
        case amount
        case type
        case currency
        case date
        case description
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(amount, forKey: .amount)
        try container.encode(type, forKey: .type)
        try container.encode(currency, forKey: .currency)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


extension Transaction: Identifiable {}
