//
// TransactionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Whether a transaction is an outgoing expense or incoming income. */
public enum TransactionType: String, Sendable, Codable, CaseIterable {
    case expense = "EXPENSE"
    case income = "INCOME"
}
